# Generated by Django 4.2.2 on 2023-07-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
