# Generated by Django 4.2.2 on 2023-07-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pint', '0003_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='userpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('title', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
