# Generated by Django 4.2.2 on 2023-07-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pint', '0006_remove_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userpost',
        ),
    ]
