# Generated by Django 4.2.2 on 2023-07-20 06:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pint', '0007_delete_userpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=ckeditor.fields.RichTextField(max_length=200, null=True),
        ),
    ]
