# Generated by Django 4.2.2 on 2023-07-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pint', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
