# Generated by Django 4.2.2 on 2023-07-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pint', '0011_post_var'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
