# Generated by Django 4.2.2 on 2023-08-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pint', '0016_alter_post_create_date_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
