# Generated by Django 4.2.2 on 2023-08-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pint', '0017_alter_comment_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='post_related',
        ),
    ]
