# Generated by Django 4.2.2 on 2023-08-09 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pint', '0019_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_dp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pint.profile'),
        ),
    ]
