# Generated by Django 4.2.2 on 2023-08-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pint', '0020_comment_author_dp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_related',
            new_name='related',
        ),
    ]
