# Generated by Django 4.2.2 on 2023-08-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pint', '0023_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='malik',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='malik_post',
        ),
    ]
