# Generated by Django 4.2.2 on 2023-08-18 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pint', '0024_rename_user_like_malik_rename_post_like_malik_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', through='pint.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
