# Generated by Django 4.2.2 on 2023-08-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pint', '0025_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture'),
        ),
    ]
